### ISSUE TITLE
Zarr has problems due to: Object of type int32 is not JSON serializable

### ISSUE THREAD

**Issue by nmeskini** [CSC-DPR/eopf-cpm#177]
Zarr has problems due to: Object of type int32 is not JSON serializable
    - Observed on: OLCI
    - Action: check code

**Comment by Kobajaski** [comment]
stackoverflow seems to registred a similar issue : 
https://stackoverflow.com/questions/50916422/python-typeerror-object-of-type-int64-is-not-json-serializable

**Comment by LidiaBaciu** [comment]
@Kobajaski we provided a possible fix here: https://github.com/CSC-DPR/eopf-cpm/commit/2ba70a20d20f8b83e585d3a39410001e54a7a7d5
it seems to work for OLCI and SY, but for SLSTR we need to fix some more issues before checking this
