### ISSUE TITLE
EOSafeStore integration of the current Accessors and new ones

### ISSUE THREAD

**Issue by nmeskini** [CSC-DPR/eopf-cpm#220]

**Comment by Kobajaski** [comment]
Martin provide some information about S2 accessors : 
- jp2spatialref shall convert the projection information contained in the Jpeg2000 file into a grid_mapping
    variable in the sense of the CF convention.
    The variable has just attributes, no value of any meaning, and among the attributes the crt_wkt.
    There should be a function in pyproj to set the attributes.

- jp2_flag_masks shall convert the variable into a flag_masks variable with the corresponding two attributes
    flag_masks and flag_meanings. You find them with the parameters.
    The semantics of the values of this variable is a bit pattern.
    You can find more information on that in the CF conventions. Simply search for flag_masks.

- jp2_flag_values is similar. Just, the values are not considered as bit patterns but as numbers that have a meaning each.

- The target path may be the same for attributes.
    Then, please merge the structures. Do we have same target paths for common variables as well? It may be a mistake.
