### ISSUE TITLE
L0+ &  Breakpoints 

### ISSUE THREAD

**Issue by nmeskini** [CSC-DPR/eopf-cpm#248]

**Comment by martin-boettcher** [comment]
In the current breakpoint prototype implementation there is an additional parameter computing_config between the input product parameters and the processing parameters provided as kwargs. Furthermore, the input product parameters are positional parameters in the moment. 
Shall we consider 
- to convert the input product parameters to (optionally) named parameters?
- to rename the "computing_config" to "context" to avoid that it is used for processor parameters?
- to move context it to the first position?
context shall be used to switch on breakpoints, switched off ("skip") by default. context could further be used for other purposes as well, e.g. to switch on or off profiling, or to collect progress or maybe also logging information in a distributed system, unless solved by dask in a different way.
